### ISSUE TITLE
Push new branch with new module: website_sale_float_qty

### ISSUE THREAD

**Issue by StefanWiselka-Solvti** [Mint-System/Odoo-Apps-Website#1]
Hi @janikvonrotz 
I would like to publish my local branch: **website-sale-float-qty_module-implementation**
which includes first version of migrated module **website_sale_float_qty**.
Unfortunately, I am not allow pushing it, according to access rights.
Could you fix the issue or give me instruction?

Stefan from Solvti

![image](https://github.com/Mint-System/Odoo-Apps-Website/assets/28051592/a7d2c490-dfb7-4c3f-9a7a-6f0787a7b4f0)

**Comment by janikvonrotz** [comment]
@MriV13 Thanks for the notice. Can you fork the repo to your account. Set it as new git origin, push and then submit the pull request? 

Guide: https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by StefanWiselka-Solvti** [comment]
@janikvonrotz Thanks for quick response.
Sure, I'll do it like you requested.

My status update:
- Managed to developed/migrated most of the functionality. Some small issues needs to be fixed and module will be ready.
- Spent 12 work hours so far.

Closing this issue.
